
-- ==============================================================================
-- DATABASE MODELO (FULL CONSOLIDATED SCRIPT)
-- Generated by Antigravity - Incorporates all recent fixes (Views, Triggers, RLS)
-- ==============================================================================

-- 1. BASE CONFIG & EXTENSIONS
-- ==============================================================================
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. ENUM TYPES
-- ==============================================================================
DO $$ BEGIN
    CREATE TYPE public.estado_cerda AS ENUM ('vacia', 'gestante', 'lactante', 'descarte');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE public.estado_lote AS ENUM ('activo', 'cerrado_vendido');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE public.tipo_flujo AS ENUM ('operativo', 'inversion', 'administrativo');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE public.tipo_insumo AS ENUM ('alimento', 'medicamento', 'biologico', 'material', 'otro');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE public.unidad_medida AS ENUM ('kg', 'gr', 'ml', 'dosis', 'unidad', 'bulto');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- 2.1 CORRALES ENUM (New)
DO $$ BEGIN
    CREATE TYPE public.tipo_corral AS ENUM ('gestacion', 'paridera', 'precebo', 'engorde', 'cuarentena');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- 3. FUNCTIONS & TRIGGERS LOGIC (Pre-Tables)
-- ==============================================================================

-- 3.1 CALCULAR PROMEDIO PONDERADO
CREATE OR REPLACE FUNCTION public.calcular_promedio_ponderado() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    v_stock_actual numeric;
    v_costo_actual numeric;
    v_cantidad_ingresada numeric;
    v_factor_conversion numeric;
    v_nuevo_costo numeric;
BEGIN
    SELECT stock_actual, costo_promedio, presentacion_compra 
    INTO v_stock_actual, v_costo_actual, v_factor_conversion
    FROM insumos WHERE id = NEW.insumo_id;

    v_cantidad_ingresada := NEW.cantidad_comprada * v_factor_conversion;
    NEW.cantidad_real_ingresada := v_cantidad_ingresada;
    
    IF v_cantidad_ingresada > 0 THEN
        NEW.precio_unitario_final := NEW.precio_total_factura / v_cantidad_ingresada;
    ELSE
        NEW.precio_unitario_final := 0;
    END IF;

    IF (v_stock_actual + v_cantidad_ingresada) > 0 THEN
        v_nuevo_costo := ((v_stock_actual * v_costo_actual) + NEW.precio_total_factura) / 
                        (v_stock_actual + v_cantidad_ingresada);
    ELSE
        v_nuevo_costo := v_costo_actual;
    END IF;

    UPDATE insumos
    SET 
        costo_promedio = v_nuevo_costo,
        stock_actual = stock_actual + v_cantidad_ingresada
    WHERE id = NEW.insumo_id;

    RETURN NEW;
END;
$$;

-- 3.2 RESTAR INVENTARIO
CREATE OR REPLACE FUNCTION public.restar_inventario() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE insumos
    SET stock_actual = GREATEST(0, stock_actual - NEW.cantidad)
    WHERE id = NEW.insumo_id;
    RETURN NEW;
END;
$$;

-- 3.3 CALCULAR FECHA PARTO PROBABLE (New)
CREATE OR REPLACE FUNCTION public.calcular_fecha_parto_probable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.fecha_inseminacion IS NOT NULL AND NEW.fecha_parto_probable IS NULL THEN
        NEW.fecha_parto_probable := NEW.fecha_inseminacion + INTERVAL '114 days';
    END IF;
    return NEW;
END;
$$;

-- 4. TABLES STRUCTURE
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.corrales (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    tipo public.tipo_corral NOT NULL,
    capacidad_maxima integer DEFAULT 10,
    activo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.categorias_financieras (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    tipo_flujo public.tipo_flujo NOT NULL,
    descripcion text,
    created_at timestamp with time zone DEFAULT now(),
    es_automatica boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.cerdas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapeta text NOT NULL UNIQUE,
    fecha_nacimiento date,
    raza text,
    estado public.estado_cerda DEFAULT 'vacia',
    partos_acumulados integer DEFAULT 0,
    activa boolean DEFAULT true,
    notas text,
    created_at timestamp with time zone DEFAULT now(),
    corral_id bigint REFERENCES public.corrales(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.ciclos_reproductivos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cerda_id bigint REFERENCES public.cerdas(id) ON DELETE CASCADE,
    fecha_inseminacion date,
    padre_semen text,
    costo_servicio numeric DEFAULT 0,
    fecha_parto_probable date,
    fecha_parto_real date,
    nacidos_vivos integer DEFAULT 0,
    nacidos_muertos integer DEFAULT 0,
    momias integer DEFAULT 0,
    fecha_destete date,
    lechones_destetados integer DEFAULT 0,
    peso_promedio_destete numeric,
    estado text DEFAULT 'abierto',
    created_at timestamp with time zone DEFAULT now(),
    observaciones text
);

CREATE TABLE IF NOT EXISTS public.insumos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    tipo public.tipo_insumo NOT NULL,
    unidad_medida public.unidad_medida DEFAULT 'kg' NOT NULL,
    presentacion_compra numeric DEFAULT 40,
    stock_actual numeric DEFAULT 0,
    costo_promedio numeric DEFAULT 0,
    stock_minimo numeric DEFAULT 5,
    activo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.compras_insumos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha date DEFAULT CURRENT_DATE,
    insumo_id bigint REFERENCES public.insumos(id) ON DELETE RESTRICT,
    proveedor text,
    cantidad_comprada numeric NOT NULL,
    cantidad_real_ingresada numeric,
    precio_total_factura numeric NOT NULL,
    precio_unitario_final numeric,
    numero_factura text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.lotes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo text NOT NULL UNIQUE,
    fecha_inicio date DEFAULT CURRENT_DATE,
    fecha_cierre date,
    ubicacion text DEFAULT 'precebo',
    cantidad_inicial integer NOT NULL,
    cantidad_actual integer NOT NULL,
    costo_inicial_lote numeric DEFAULT 0,
    estado public.estado_lote DEFAULT 'activo',
    created_at timestamp with time zone DEFAULT now(),
    peso_promedio_inicial numeric DEFAULT 0,
    observaciones text,
    peso_promedio_actual numeric DEFAULT 0,
    corral_id bigint REFERENCES public.corrales(id) ON DELETE SET NULL,
    etapa text DEFAULT 'precebo' CHECK (etapa IN ('precebo', 'engorde'))
);

CREATE TABLE IF NOT EXISTS public.lote_origen (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_id bigint REFERENCES public.lotes(id) ON DELETE CASCADE,
    ciclo_id bigint REFERENCES public.ciclos_reproductivos(id) ON DELETE CASCADE,
    cantidad_aportada integer,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.movimientos_caja (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha date DEFAULT CURRENT_DATE,
    tipo text CHECK (tipo IN ('ingreso', 'egreso')),
    categoria_id bigint REFERENCES public.categorias_financieras(id) ON DELETE RESTRICT,
    monto numeric NOT NULL,
    descripcion text,
    metodo_pago text DEFAULT 'efectivo',
    lote_relacionado_id bigint REFERENCES public.lotes(id) ON DELETE SET NULL,
    url_comprobante text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.salidas_insumos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha date DEFAULT CURRENT_DATE,
    insumo_id bigint REFERENCES public.insumos(id) ON DELETE RESTRICT,
    cantidad numeric NOT NULL,
    destino_tipo text CHECK (destino_tipo IN ('lote', 'cerda', 'general')),
    lote_id bigint REFERENCES public.lotes(id) ON DELETE SET NULL,
    cerda_id bigint REFERENCES public.cerdas(id) ON DELETE SET NULL,
    costo_unitario_momento numeric NOT NULL,
    costo_total_salida numeric GENERATED ALWAYS AS ((cantidad * costo_unitario_momento)) STORED,
    notas text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.eventos_sanitarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha date DEFAULT CURRENT_DATE,
    tipo text CHECK (tipo IN ('muerte', 'enfermedad', 'tratamiento')),
    lote_id bigint REFERENCES public.lotes(id) ON DELETE SET NULL,
    cerda_id bigint REFERENCES public.cerdas(id) ON DELETE SET NULL,
    cantidad_afectada integer DEFAULT 1,
    observacion text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.reglas_sanitarias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tarea text NOT NULL,
    dias_target integer NOT NULL,
    evento_origen text NOT NULL CHECK (evento_origen IN ('parto', 'naciomiento', 'servicio', 'destete', 'inicio_lote', 'nacimiento')),
    tipo_aplicacion text NOT NULL CHECK (tipo_aplicacion IN ('madre', 'camada', 'lote')),
    obligatorio boolean DEFAULT true,
    activo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

-- 5. ATTACH TRIGGERS
-- ==============================================================================
DROP TRIGGER IF EXISTS trg_calcular_fecha_parto ON public.ciclos_reproductivos;
CREATE TRIGGER trg_calcular_fecha_parto BEFORE INSERT ON public.ciclos_reproductivos FOR EACH ROW EXECUTE FUNCTION public.calcular_fecha_parto_probable();

DROP TRIGGER IF EXISTS trg_actualizar_inventario_compra ON public.compras_insumos;
CREATE TRIGGER trg_actualizar_inventario_compra BEFORE INSERT ON public.compras_insumos FOR EACH ROW EXECUTE FUNCTION public.calcular_promedio_ponderado();

DROP TRIGGER IF EXISTS trg_restar_inventario_salida ON public.salidas_insumos;
CREATE TRIGGER trg_restar_inventario_salida AFTER INSERT ON public.salidas_insumos FOR EACH ROW EXECUTE FUNCTION public.restar_inventario();

-- 6. VIEWS (CONSOLIDATED)
-- ==============================================================================

-- 6.1 VISTA ESTADO CORRALES
CREATE OR REPLACE VIEW public.vista_estado_corrales AS
SELECT 
    c.id,
    c.nombre,
    c.tipo,
    c.capacidad_maxima,
    COALESCE((SELECT SUM(l.cantidad_actual) FROM public.lotes l WHERE l.corral_id = c.id AND l.estado = 'activo'), 0) as ocupacion_lotes,
    COALESCE((SELECT COUNT(*) FROM public.cerdas m WHERE m.corral_id = c.id AND m.activa = true), 0) as ocupacion_cerdas,
    (
        COALESCE((SELECT SUM(l.cantidad_actual) FROM public.lotes l WHERE l.corral_id = c.id AND l.estado = 'activo'), 0) +
        COALESCE((SELECT COUNT(*) FROM public.cerdas m WHERE m.corral_id = c.id AND m.activa = true), 0)
    ) as ocupacion_total
FROM public.corrales c
WHERE c.activo = true;

-- 6.2 REPORTE GASTOS CATEGORIA
CREATE OR REPLACE VIEW public.reporte_gastos_categoria AS
SELECT to_char((m.fecha)::timestamp with time zone, 'YYYY-MM'::text) AS mes,
    c.nombre AS categoria_nombre,
    c.tipo_flujo,
    sum(m.monto) AS total_gastado,
    count(m.id) AS cantidad_movimientos
FROM (public.movimientos_caja m
    JOIN public.categorias_financieras c ON ((m.categoria_id = c.id)))
WHERE (m.tipo = 'egreso'::text)
GROUP BY (to_char((m.fecha)::timestamp with time zone, 'YYYY-MM'::text)), c.nombre, c.tipo_flujo
ORDER BY (to_char((m.fecha)::timestamp with time zone, 'YYYY-MM'::text)) DESC, (sum(m.monto)) DESC;

-- 6.3 REPORTE RENTABILIDAD LOTE
CREATE OR REPLACE VIEW public.reporte_rentabilidad_lote AS
SELECT l.id,
    l.codigo,
    l.estado,
    l.cantidad_inicial,
    l.cantidad_actual,
    l.costo_inicial_lote AS inversion_animales,
    COALESCE(sum(s.costo_total_salida), (0)::numeric) AS costo_alimentacion,
    (l.costo_inicial_lote + COALESCE(sum(s.costo_total_salida), (0)::numeric)) AS costo_total_acumulado,
    COALESCE(( SELECT sum(movimientos_caja.monto) AS sum
            FROM public.movimientos_caja
            WHERE ((movimientos_caja.lote_relacionado_id = l.id) AND (movimientos_caja.tipo = 'ingreso'::text))), (0)::numeric) AS total_ventas,
    (COALESCE(( SELECT sum(movimientos_caja.monto) AS sum
            FROM public.movimientos_caja
            WHERE ((movimientos_caja.lote_relacionado_id = l.id) AND (movimientos_caja.tipo = 'ingreso'::text))), (0)::numeric) - (l.costo_inicial_lote + COALESCE(sum(s.costo_total_salida), (0)::numeric))) AS ganancia_neta
FROM (public.lotes l
    LEFT JOIN public.salidas_insumos s ON ((l.id = s.lote_id)))
GROUP BY l.id, l.codigo, l.estado, l.cantidad_inicial, l.cantidad_actual, l.costo_inicial_lote;

-- 6.4 REPORTE FLUJO CAJA MENSUAL (New)
CREATE OR REPLACE VIEW public.reporte_flujo_caja_mensual AS
 SELECT to_char((movimientos_caja.fecha)::timestamp with time zone, 'YYYY-MM'::text) AS mes,
    c.nombre AS categoria_nombre,
    movimientos_caja.tipo,
    sum(movimientos_caja.monto) AS total
   FROM (public.movimientos_caja
     JOIN public.categorias_financieras c ON ((movimientos_caja.categoria_id = c.id)))
  GROUP BY (to_char((movimientos_caja.fecha)::timestamp with time zone, 'YYYY-MM'::text)), c.nombre, movimientos_caja.tipo
  ORDER BY (to_char((movimientos_caja.fecha)::timestamp with time zone, 'YYYY-MM'::text)) DESC;

-- 6.5 REPORTE COSTOS MATERNIDAD (New)
CREATE OR REPLACE VIEW public.reporte_costos_maternidad AS
 WITH gastos_insumos AS (
         SELECT to_char((salidas_insumos.fecha)::timestamp with time zone, 'YYYY-MM'::text) AS mes,
            COALESCE(sum(salidas_insumos.costo_total_salida), (0)::numeric) AS total
           FROM public.salidas_insumos
          WHERE (salidas_insumos.destino_tipo = 'cerda'::text)
          GROUP BY (to_char((salidas_insumos.fecha)::timestamp with time zone, 'YYYY-MM'::text))
        ), gastos_semen AS (
         SELECT to_char((ciclos_reproductivos.fecha_inseminacion)::timestamp with time zone, 'YYYY-MM'::text) AS mes,
            COALESCE(sum(ciclos_reproductivos.costo_servicio), (0)::numeric) AS total
           FROM public.ciclos_reproductivos
          WHERE (ciclos_reproductivos.fecha_inseminacion IS NOT NULL)
          GROUP BY (to_char((ciclos_reproductivos.fecha_inseminacion)::timestamp with time zone, 'YYYY-MM'::text))
        ), produccion_mensual AS (
         SELECT to_char((ciclos_reproductivos.fecha_destete)::timestamp with time zone, 'YYYY-MM'::text) AS mes,
            COALESCE(sum(ciclos_reproductivos.lechones_destetados), (0)::bigint) AS total_lechones
           FROM public.ciclos_reproductivos
          WHERE (ciclos_reproductivos.fecha_destete IS NOT NULL)
          GROUP BY (to_char((ciclos_reproductivos.fecha_destete)::timestamp with time zone, 'YYYY-MM'::text))
        )
 SELECT COALESCE(g.mes, s.mes, p.mes) AS mes,
    (COALESCE(g.total, (0)::numeric) + COALESCE(s.total, (0)::numeric)) AS total_gastos_madres,
    COALESCE(p.total_lechones, (0)::bigint) AS total_lechones_producidos,
        CASE
            WHEN (COALESCE(p.total_lechones, (0)::bigint) > 0) THEN ((COALESCE(g.total, (0)::numeric) + COALESCE(s.total, (0)::numeric)) / (p.total_lechones)::numeric)
            ELSE (0)::numeric
        END AS costo_por_lechon
   FROM ((gastos_insumos g
     FULL JOIN gastos_semen s ON ((g.mes = s.mes)))
     FULL JOIN produccion_mensual p ON ((COALESCE(g.mes, s.mes) = p.mes)))
  ORDER BY COALESCE(g.mes, s.mes, p.mes) DESC;

-- 7. RLS & POLICIES (SECURITY)
-- ==============================================================================

-- Enable RLS
ALTER TABLE public.cerdas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ciclos_reproductivos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eventos_sanitarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimientos_caja ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compras_insumos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.salidas_insumos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.insumos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorias_financieras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reglas_sanitarias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lote_origen ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.corrales ENABLE ROW LEVEL SECURITY;

-- Allow 'authenticated' (App Users) full access
CREATE POLICY "Acceso total a usuarios autenticados" ON public.cerdas TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total lotes" ON public.lotes TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total ciclos" ON public.ciclos_reproductivos TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total eventos" ON public.eventos_sanitarios TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total caja" ON public.movimientos_caja TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total compras" ON public.compras_insumos TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total salidas" ON public.salidas_insumos TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total insumos" ON public.insumos TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total categorias" ON public.categorias_financieras TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total a reglas sanitarias" ON public.reglas_sanitarias TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total lote_origen" ON public.lote_origen TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total corrales" ON public.corrales TO authenticated USING (true) WITH CHECK (true);

-- Extra READ access
CREATE POLICY "Public read access" ON public.reglas_sanitarias FOR SELECT USING (true);
GRANT SELECT ON public.reporte_flujo_caja_mensual TO anon, authenticated, service_role;
GRANT SELECT ON public.reporte_costos_maternidad TO anon, authenticated, service_role;
GRANT SELECT ON public.vista_estado_corrales TO anon, authenticated, service_role;
GRANT SELECT ON public.reporte_rentabilidad_lote TO anon, authenticated, service_role;
GRANT SELECT ON public.reporte_gastos_categoria TO anon, authenticated, service_role;

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated, service_role;

-- 8. SEED DATA (CATALOGOS)
-- ==============================================================================

-- A. CATEGORÍAS FINANCIERAS
INSERT INTO categorias_financieras (nombre, tipo_flujo, descripcion, es_automatica) VALUES
('Venta de Cerdos', 'operativo', 'Venta de animales de engorde (automática)', true),
('Venta de Cerda Descarte', 'operativo', 'Ingreso por venta de cerdas de descarte (automática)', true),
('Venta de Lechones', 'operativo', 'Venta de destetes (automática)', true),
('Compra Alimento', 'operativo', 'Concentrados y materia prima', false),
('Medicamentos', 'operativo', 'Insumos veterinarios y vacunas', false),
('Compra de Semen/Genética', 'operativo', 'Pago por pajillas o servicios de monta', false),
('Compra Materiales/Insumos', 'operativo', 'Agujas, desinfectantes, herramientas', false),
('Nomina', 'operativo', 'Pago de personal', false),
('Mantenimiento', 'operativo', 'Reparaciones locativas y equipos', false),
('Transporte', 'operativo', 'Fletes y movilización de animales', false),
('Compra de Pie de Cría', 'inversion', 'Compra de cerdas madres o verracos', false),
('Infraestructura', 'inversion', 'Construcción de corrales y bodegas', false),
('Maquinaria y Equipo', 'inversion', 'Herramientas de larga duración', false),
('Servicios Publicos', 'administrativo', 'Luz, Agua, Gas, Internet', false),
('Impuestos y Legal', 'administrativo', 'Gastos bancarios y legales', false),
('Venta de Abono/Porquinaza', 'operativo', 'Subproductos', false),
('Venta de Costales', 'operativo', 'Reciclaje', false),
('Prestamos / Aportes', 'operativo', 'Dinero externo o socios', false)
ON CONFLICT DO NOTHING;

-- B. INSUMOS 
INSERT INTO insumos (nombre, tipo, unidad_medida, presentacion_compra, stock_minimo) VALUES
('Lactancia', 'alimento', 'kg', 40, 150),
('Pre-Inicio Fase 1', 'alimento', 'kg', 40, 100),
('Pre-Inicio', 'alimento', 'kg', 40, 100),
('Inicio', 'alimento', 'kg', 40, 200),
('Lechón Transición', 'alimento', 'kg', 40, 200),
('Lechón 337', 'alimento', 'kg', 40, 300),
('Finalizador 337', 'alimento', 'kg', 40, 500),
('Hierro Dextrano', 'medicamento', 'ml', 100, 50),
('Baycox (Toltrazuril)', 'medicamento', 'ml', 250, 20),
('Vacuna Circovirus + Mycoplasma', 'biologico', 'dosis', 50, 10),
('Vacuna E. Coli', 'biologico', 'dosis', 25, 10),
('Vacuna Eri-Parvo-Lepto', 'biologico', 'dosis', 50, 10),
('Vacuna Peste Porcina (PPC)', 'biologico', 'dosis', 50, 10),
('Ivermectina 1%', 'medicamento', 'ml', 500, 50),
('Purgante Oral (Fenbendazol)', 'medicamento', 'ml', 1000, 100),
('Vitaminas AD3E', 'medicamento', 'ml', 250, 20),
('Agujas', 'material', 'unidad', 100, 50),
('Yodo', 'material', 'ml', 1000, 200)
ON CONFLICT DO NOTHING;

-- C. REGLAS SANITARIAS
INSERT INTO reglas_sanitarias (nombre_tarea, dias_target, evento_origen, tipo_aplicacion, obligatorio, activo) VALUES
('Aplicar Hierro + Anticoccidial', 3, 'parto', 'camada', true, true),
('Vacuna Circovirus + Mycoplasma (Dosis 1)', 7, 'parto', 'camada', true, true),
('Vacuna Circovirus + Mycoplasma (Dosis 2)', 21, 'parto', 'camada', true, true),
('Reemplazo: Vacuna Circovirus + Mycoplasma (145 días)', 145, 'nacimiento', 'madre', true, true),
('Reemplazo: Vacuna Eri-Parvo-Lepto (155 días)', 155, 'nacimiento', 'madre', true, true),
('Primeriza: Vacuna E.Coli (75 días gestación)', 75, 'servicio', 'madre', true, true),
('Multípara: Vacuna E.Coli (90 días gestación)', 90, 'servicio', 'madre', true, true),
('Choque Vitamínico Llegada', 1, 'inicio_lote', 'lote', true, true)
ON CONFLICT DO NOTHING;

-- ==============================================================================
-- END OF SCRIPT
-- ==============================================================================
