--
-- PostgreSQL database dump
--

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.0

-- Started on 2025-11-28 11:52:35

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 17 (class 2615 OID 17487)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- TOC entry 1242 (class 1247 OID 17514)
-- Name: estado_cerda; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.estado_cerda AS ENUM (
    'vacia',
    'gestante',
    'lactante',
    'descarte'
);


--
-- TOC entry 1245 (class 1247 OID 17524)
-- Name: estado_lote; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.estado_lote AS ENUM (
    'activo',
    'cerrado_vendido'
);


--
-- TOC entry 1248 (class 1247 OID 17530)
-- Name: tipo_flujo; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.tipo_flujo AS ENUM (
    'operativo',
    'inversion',
    'administrativo'
);


--
-- TOC entry 1234 (class 1247 OID 17489)
-- Name: tipo_insumo; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.tipo_insumo AS ENUM (
    'alimento',
    'medicamento',
    'biologico',
    'material',
    'otro'
);


--
-- TOC entry 1239 (class 1247 OID 17500)
-- Name: unidad_medida; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.unidad_medida AS ENUM (
    'kg',
    'gr',
    'ml',
    'dosis',
    'unidad',
    'bulto'
);


--
-- TOC entry 517 (class 1255 OID 17713)
-- Name: calcular_promedio_ponderado(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.calcular_promedio_ponderado() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_stock_actual numeric;
    v_costo_actual numeric;
    v_cantidad_ingresada numeric;
    v_factor_conversion numeric;
    v_nuevo_costo numeric;
BEGIN
    -- Obtenemos datos actuales
    SELECT stock_actual, costo_promedio, presentacion_compra 
    INTO v_stock_actual, v_costo_actual, v_factor_conversion
    FROM insumos WHERE id = NEW.insumo_id;

    -- Calculamos kilos reales
    v_cantidad_ingresada := NEW.cantidad_comprada * v_factor_conversion;
    NEW.cantidad_real_ingresada := v_cantidad_ingresada;
    
    -- Evitar división por cero
    IF v_cantidad_ingresada > 0 THEN
        NEW.precio_unitario_final := NEW.precio_total_factura / v_cantidad_ingresada;
    ELSE
        NEW.precio_unitario_final := 0;
    END IF;

    -- Calcular nuevo costo promedio ponderado
    IF (v_stock_actual + v_cantidad_ingresada) > 0 THEN
        v_nuevo_costo := ((v_stock_actual * v_costo_actual) + NEW.precio_total_factura) / 
                        (v_stock_actual + v_cantidad_ingresada);
    ELSE
        v_nuevo_costo := v_costo_actual;
    END IF;

    -- Actualizamos Insumo con nuevo precio promedio
    UPDATE insumos
    SET 
        costo_promedio = v_nuevo_costo,
        stock_actual = stock_actual + v_cantidad_ingresada
    WHERE id = NEW.insumo_id;

    RETURN NEW;
END;
$$;


--
-- TOC entry 518 (class 1255 OID 17715)
-- Name: restar_inventario(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.restar_inventario() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    UPDATE insumos
    SET stock_actual = GREATEST(0, stock_actual - NEW.cantidad)
    WHERE id = NEW.insumo_id;
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 370 (class 1259 OID 17538)
-- Name: categorias_financieras; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categorias_financieras (
    id bigint NOT NULL,
    nombre text NOT NULL,
    tipo_flujo public.tipo_flujo NOT NULL,
    descripcion text,
    created_at timestamp with time zone DEFAULT now(),
    es_automatica boolean DEFAULT false
);


--
-- TOC entry 369 (class 1259 OID 17537)
-- Name: categorias_financieras_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categorias_financieras ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_financieras_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 374 (class 1259 OID 17562)
-- Name: cerdas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cerdas (
    id bigint NOT NULL,
    chapeta text NOT NULL,
    fecha_nacimiento date,
    raza text,
    estado public.estado_cerda DEFAULT 'vacia'::public.estado_cerda,
    partos_acumulados integer DEFAULT 0,
    activa boolean DEFAULT true,
    notas text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- TOC entry 373 (class 1259 OID 17561)
-- Name: cerdas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cerdas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cerdas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 376 (class 1259 OID 17576)
-- Name: ciclos_reproductivos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ciclos_reproductivos (
    id bigint NOT NULL,
    cerda_id bigint,
    fecha_inseminacion date,
    padre_semen text,
    costo_servicio numeric DEFAULT 0,
    fecha_parto_probable date,
    fecha_parto_real date,
    nacidos_vivos integer DEFAULT 0,
    nacidos_muertos integer DEFAULT 0,
    momias integer DEFAULT 0,
    fecha_destete date,
    lechones_destetados integer DEFAULT 0,
    peso_promedio_destete numeric,
    estado text DEFAULT 'abierto'::text,
    created_at timestamp with time zone DEFAULT now(),
    observaciones text
);


--
-- TOC entry 375 (class 1259 OID 17575)
-- Name: ciclos_reproductivos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ciclos_reproductivos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ciclos_reproductivos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 382 (class 1259 OID 17628)
-- Name: compras_insumos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.compras_insumos (
    id bigint NOT NULL,
    fecha date DEFAULT CURRENT_DATE,
    insumo_id bigint,
    proveedor text,
    cantidad_comprada numeric NOT NULL,
    cantidad_real_ingresada numeric,
    precio_total_factura numeric NOT NULL,
    precio_unitario_final numeric,
    numero_factura text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- TOC entry 381 (class 1259 OID 17627)
-- Name: compras_insumos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.compras_insumos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compras_insumos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 388 (class 1259 OID 17692)
-- Name: eventos_sanitarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eventos_sanitarios (
    id bigint NOT NULL,
    fecha date DEFAULT CURRENT_DATE,
    tipo text,
    lote_id bigint,
    cerda_id bigint,
    cantidad_afectada integer DEFAULT 1,
    observacion text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT eventos_sanitarios_tipo_check CHECK ((tipo = ANY (ARRAY['muerte'::text, 'enfermedad'::text, 'tratamiento'::text])))
);


--
-- TOC entry 387 (class 1259 OID 17691)
-- Name: eventos_sanitarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.eventos_sanitarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_sanitarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 372 (class 1259 OID 17547)
-- Name: insumos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.insumos (
    id bigint NOT NULL,
    nombre text NOT NULL,
    tipo public.tipo_insumo NOT NULL,
    unidad_medida public.unidad_medida DEFAULT 'kg'::public.unidad_medida NOT NULL,
    presentacion_compra numeric DEFAULT 40,
    stock_actual numeric DEFAULT 0,
    costo_promedio numeric DEFAULT 0,
    stock_minimo numeric DEFAULT 5,
    activo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);


--
-- TOC entry 371 (class 1259 OID 17546)
-- Name: insumos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.insumos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.insumos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 380 (class 1259 OID 17611)
-- Name: lote_origen; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lote_origen (
    id bigint NOT NULL,
    lote_id bigint,
    ciclo_id bigint,
    cantidad_aportada integer,
    created_at timestamp with time zone DEFAULT now()
);


--
-- TOC entry 379 (class 1259 OID 17610)
-- Name: lote_origen_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lote_origen ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lote_origen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 378 (class 1259 OID 17596)
-- Name: lotes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lotes (
    id bigint NOT NULL,
    codigo text NOT NULL,
    fecha_inicio date DEFAULT CURRENT_DATE,
    fecha_cierre date,
    ubicacion text DEFAULT 'precebo'::text,
    cantidad_inicial integer NOT NULL,
    cantidad_actual integer NOT NULL,
    costo_inicial_lote numeric DEFAULT 0,
    estado public.estado_lote DEFAULT 'activo'::public.estado_lote,
    created_at timestamp with time zone DEFAULT now(),
    peso_promedio_inicial numeric DEFAULT 0,
    observaciones text,
    peso_promedio_actual numeric DEFAULT 0
);


--
-- TOC entry 377 (class 1259 OID 17595)
-- Name: lotes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lotes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lotes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 386 (class 1259 OID 17670)
-- Name: movimientos_caja; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movimientos_caja (
    id bigint NOT NULL,
    fecha date DEFAULT CURRENT_DATE,
    tipo text,
    categoria_id bigint,
    monto numeric NOT NULL,
    descripcion text,
    metodo_pago text DEFAULT 'efectivo'::text,
    lote_relacionado_id bigint,
    url_comprobante text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT movimientos_caja_tipo_check CHECK ((tipo = ANY (ARRAY['ingreso'::text, 'egreso'::text])))
);


--
-- TOC entry 385 (class 1259 OID 17669)
-- Name: movimientos_caja_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.movimientos_caja ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimientos_caja_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 384 (class 1259 OID 17643)
-- Name: salidas_insumos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.salidas_insumos (
    id bigint NOT NULL,
    fecha date DEFAULT CURRENT_DATE,
    insumo_id bigint,
    cantidad numeric NOT NULL,
    destino_tipo text,
    lote_id bigint,
    cerda_id bigint,
    costo_unitario_momento numeric NOT NULL,
    costo_total_salida numeric GENERATED ALWAYS AS ((cantidad * costo_unitario_momento)) STORED,
    notas text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT salidas_insumos_destino_tipo_check CHECK ((destino_tipo = ANY (ARRAY['lote'::text, 'cerda'::text, 'general'::text])))
);


--
-- TOC entry 390 (class 1259 OID 22190)
-- Name: reporte_costos_maternidad; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.reporte_costos_maternidad AS
 WITH gastos_mensuales AS (
         SELECT to_char((salidas_insumos.fecha)::timestamp with time zone, 'YYYY-MM'::text) AS mes,
            COALESCE(sum(salidas_insumos.costo_total_salida), (0)::numeric) AS total_gastos
           FROM public.salidas_insumos
          WHERE (salidas_insumos.destino_tipo = 'cerda'::text)
          GROUP BY (to_char((salidas_insumos.fecha)::timestamp with time zone, 'YYYY-MM'::text))
        ), produccion_mensual AS (
         SELECT to_char((ciclos_reproductivos.fecha_destete)::timestamp with time zone, 'YYYY-MM'::text) AS mes,
            COALESCE(sum(ciclos_reproductivos.lechones_destetados), (0)::bigint) AS total_lechones
           FROM public.ciclos_reproductivos
          WHERE (ciclos_reproductivos.fecha_destete IS NOT NULL)
          GROUP BY (to_char((ciclos_reproductivos.fecha_destete)::timestamp with time zone, 'YYYY-MM'::text))
        )
 SELECT COALESCE(g.mes, p.mes) AS mes,
    COALESCE(g.total_gastos, (0)::numeric) AS total_gastos_madres,
    COALESCE(p.total_lechones, (0)::bigint) AS total_lechones_producidos,
        CASE
            WHEN (COALESCE(p.total_lechones, (0)::bigint) > 0) THEN (COALESCE(g.total_gastos, (0)::numeric) / (p.total_lechones)::numeric)
            ELSE (0)::numeric
        END AS costo_por_lechon
   FROM (gastos_mensuales g
     FULL JOIN produccion_mensual p ON ((g.mes = p.mes)))
  ORDER BY COALESCE(g.mes, p.mes) DESC;


--
-- TOC entry 391 (class 1259 OID 23622)
-- Name: reporte_gastos_categoria; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.reporte_gastos_categoria AS
 SELECT to_char((m.fecha)::timestamp with time zone, 'YYYY-MM'::text) AS mes,
    c.nombre AS categoria_nombre,
    c.tipo_flujo,
    sum(m.monto) AS total_gastado,
    count(m.id) AS cantidad_movimientos
   FROM (public.movimientos_caja m
     JOIN public.categorias_financieras c ON ((m.categoria_id = c.id)))
  WHERE (m.tipo = 'egreso'::text)
  GROUP BY (to_char((m.fecha)::timestamp with time zone, 'YYYY-MM'::text)), c.nombre, c.tipo_flujo
  ORDER BY (to_char((m.fecha)::timestamp with time zone, 'YYYY-MM'::text)) DESC, (sum(m.monto)) DESC;


--
-- TOC entry 389 (class 1259 OID 22142)
-- Name: reporte_rentabilidad_lote; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.reporte_rentabilidad_lote AS
 SELECT l.id,
    l.codigo,
    l.estado,
    l.cantidad_inicial,
    l.cantidad_actual,
    l.costo_inicial_lote AS inversion_animales,
    COALESCE(sum(s.costo_total_salida), (0)::numeric) AS costo_alimentacion,
    (l.costo_inicial_lote + COALESCE(sum(s.costo_total_salida), (0)::numeric)) AS costo_total_acumulado,
    COALESCE(( SELECT sum(movimientos_caja.monto) AS sum
           FROM public.movimientos_caja
          WHERE ((movimientos_caja.lote_relacionado_id = l.id) AND (movimientos_caja.tipo = 'ingreso'::text))), (0)::numeric) AS total_ventas,
    (COALESCE(( SELECT sum(movimientos_caja.monto) AS sum
           FROM public.movimientos_caja
          WHERE ((movimientos_caja.lote_relacionado_id = l.id) AND (movimientos_caja.tipo = 'ingreso'::text))), (0)::numeric) - (l.costo_inicial_lote + COALESCE(sum(s.costo_total_salida), (0)::numeric))) AS ganancia_neta
   FROM (public.lotes l
     LEFT JOIN public.salidas_insumos s ON ((l.id = s.lote_id)))
  GROUP BY l.id, l.codigo, l.estado, l.cantidad_inicial, l.cantidad_actual, l.costo_inicial_lote;


--
-- TOC entry 383 (class 1259 OID 17642)
-- Name: salidas_insumos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.salidas_insumos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.salidas_insumos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3719 (class 2606 OID 17545)
-- Name: categorias_financieras categorias_financieras_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categorias_financieras
    ADD CONSTRAINT categorias_financieras_pkey PRIMARY KEY (id);


--
-- TOC entry 3723 (class 2606 OID 17574)
-- Name: cerdas cerdas_chapeta_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cerdas
    ADD CONSTRAINT cerdas_chapeta_key UNIQUE (chapeta);


--
-- TOC entry 3725 (class 2606 OID 17572)
-- Name: cerdas cerdas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cerdas
    ADD CONSTRAINT cerdas_pkey PRIMARY KEY (id);


--
-- TOC entry 3727 (class 2606 OID 17589)
-- Name: ciclos_reproductivos ciclos_reproductivos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ciclos_reproductivos
    ADD CONSTRAINT ciclos_reproductivos_pkey PRIMARY KEY (id);


--
-- TOC entry 3735 (class 2606 OID 17636)
-- Name: compras_insumos compras_insumos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.compras_insumos
    ADD CONSTRAINT compras_insumos_pkey PRIMARY KEY (id);


--
-- TOC entry 3741 (class 2606 OID 17702)
-- Name: eventos_sanitarios eventos_sanitarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_sanitarios
    ADD CONSTRAINT eventos_sanitarios_pkey PRIMARY KEY (id);


--
-- TOC entry 3721 (class 2606 OID 17560)
-- Name: insumos insumos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.insumos
    ADD CONSTRAINT insumos_pkey PRIMARY KEY (id);


--
-- TOC entry 3733 (class 2606 OID 17616)
-- Name: lote_origen lote_origen_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lote_origen
    ADD CONSTRAINT lote_origen_pkey PRIMARY KEY (id);


--
-- TOC entry 3729 (class 2606 OID 17609)
-- Name: lotes lotes_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes
    ADD CONSTRAINT lotes_codigo_key UNIQUE (codigo);


--
-- TOC entry 3731 (class 2606 OID 17607)
-- Name: lotes lotes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes
    ADD CONSTRAINT lotes_pkey PRIMARY KEY (id);


--
-- TOC entry 3739 (class 2606 OID 17680)
-- Name: movimientos_caja movimientos_caja_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimientos_caja
    ADD CONSTRAINT movimientos_caja_pkey PRIMARY KEY (id);


--
-- TOC entry 3737 (class 2606 OID 17653)
-- Name: salidas_insumos salidas_insumos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salidas_insumos
    ADD CONSTRAINT salidas_insumos_pkey PRIMARY KEY (id);


--
-- TOC entry 3753 (class 2620 OID 17714)
-- Name: compras_insumos trg_actualizar_inventario_compra; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_actualizar_inventario_compra BEFORE INSERT ON public.compras_insumos FOR EACH ROW EXECUTE FUNCTION public.calcular_promedio_ponderado();


--
-- TOC entry 3754 (class 2620 OID 17716)
-- Name: salidas_insumos trg_restar_inventario_salida; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_restar_inventario_salida AFTER INSERT ON public.salidas_insumos FOR EACH ROW EXECUTE FUNCTION public.restar_inventario();


--
-- TOC entry 3742 (class 2606 OID 17590)
-- Name: ciclos_reproductivos ciclos_reproductivos_cerda_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ciclos_reproductivos
    ADD CONSTRAINT ciclos_reproductivos_cerda_id_fkey FOREIGN KEY (cerda_id) REFERENCES public.cerdas(id) ON DELETE CASCADE;


--
-- TOC entry 3745 (class 2606 OID 17637)
-- Name: compras_insumos compras_insumos_insumo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.compras_insumos
    ADD CONSTRAINT compras_insumos_insumo_id_fkey FOREIGN KEY (insumo_id) REFERENCES public.insumos(id) ON DELETE RESTRICT;


--
-- TOC entry 3751 (class 2606 OID 17708)
-- Name: eventos_sanitarios eventos_sanitarios_cerda_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_sanitarios
    ADD CONSTRAINT eventos_sanitarios_cerda_id_fkey FOREIGN KEY (cerda_id) REFERENCES public.cerdas(id) ON DELETE SET NULL;


--
-- TOC entry 3752 (class 2606 OID 17703)
-- Name: eventos_sanitarios eventos_sanitarios_lote_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_sanitarios
    ADD CONSTRAINT eventos_sanitarios_lote_id_fkey FOREIGN KEY (lote_id) REFERENCES public.lotes(id) ON DELETE SET NULL;


--
-- TOC entry 3743 (class 2606 OID 17622)
-- Name: lote_origen lote_origen_ciclo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lote_origen
    ADD CONSTRAINT lote_origen_ciclo_id_fkey FOREIGN KEY (ciclo_id) REFERENCES public.ciclos_reproductivos(id) ON DELETE CASCADE;


--
-- TOC entry 3744 (class 2606 OID 17617)
-- Name: lote_origen lote_origen_lote_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lote_origen
    ADD CONSTRAINT lote_origen_lote_id_fkey FOREIGN KEY (lote_id) REFERENCES public.lotes(id) ON DELETE CASCADE;


--
-- TOC entry 3749 (class 2606 OID 17681)
-- Name: movimientos_caja movimientos_caja_categoria_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimientos_caja
    ADD CONSTRAINT movimientos_caja_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.categorias_financieras(id) ON DELETE RESTRICT;


--
-- TOC entry 3750 (class 2606 OID 17686)
-- Name: movimientos_caja movimientos_caja_lote_relacionado_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimientos_caja
    ADD CONSTRAINT movimientos_caja_lote_relacionado_id_fkey FOREIGN KEY (lote_relacionado_id) REFERENCES public.lotes(id) ON DELETE SET NULL;


--
-- TOC entry 3746 (class 2606 OID 17664)
-- Name: salidas_insumos salidas_insumos_cerda_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salidas_insumos
    ADD CONSTRAINT salidas_insumos_cerda_id_fkey FOREIGN KEY (cerda_id) REFERENCES public.cerdas(id) ON DELETE SET NULL;


--
-- TOC entry 3747 (class 2606 OID 17654)
-- Name: salidas_insumos salidas_insumos_insumo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salidas_insumos
    ADD CONSTRAINT salidas_insumos_insumo_id_fkey FOREIGN KEY (insumo_id) REFERENCES public.insumos(id) ON DELETE RESTRICT;


--
-- TOC entry 3748 (class 2606 OID 17659)
-- Name: salidas_insumos salidas_insumos_lote_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salidas_insumos
    ADD CONSTRAINT salidas_insumos_lote_id_fkey FOREIGN KEY (lote_id) REFERENCES public.lotes(id) ON DELETE SET NULL;


--
-- TOC entry 3916 (class 3256 OID 22302)
-- Name: cerdas Acceso total a usuarios autenticados; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Acceso total a usuarios autenticados" ON public.cerdas TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3923 (class 3256 OID 22309)
-- Name: movimientos_caja Acceso total caja; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Acceso total caja" ON public.movimientos_caja TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3924 (class 3256 OID 22310)
-- Name: categorias_financieras Acceso total categorias; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Acceso total categorias" ON public.categorias_financieras TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3918 (class 3256 OID 22304)
-- Name: ciclos_reproductivos Acceso total ciclos; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Acceso total ciclos" ON public.ciclos_reproductivos TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3920 (class 3256 OID 22306)
-- Name: compras_insumos Acceso total compras; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Acceso total compras" ON public.compras_insumos TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3922 (class 3256 OID 22308)
-- Name: eventos_sanitarios Acceso total eventos; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Acceso total eventos" ON public.eventos_sanitarios TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3919 (class 3256 OID 22305)
-- Name: insumos Acceso total insumos; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Acceso total insumos" ON public.insumos TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3925 (class 3256 OID 22311)
-- Name: lote_origen Acceso total lote_origen; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Acceso total lote_origen" ON public.lote_origen TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3917 (class 3256 OID 22303)
-- Name: lotes Acceso total lotes; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Acceso total lotes" ON public.lotes TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3921 (class 3256 OID 22307)
-- Name: salidas_insumos Acceso total salidas; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Acceso total salidas" ON public.salidas_insumos TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3906 (class 0 OID 17538)
-- Dependencies: 370
-- Name: categorias_financieras; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.categorias_financieras ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3908 (class 0 OID 17562)
-- Dependencies: 374
-- Name: cerdas; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cerdas ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3909 (class 0 OID 17576)
-- Dependencies: 376
-- Name: ciclos_reproductivos; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ciclos_reproductivos ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3912 (class 0 OID 17628)
-- Dependencies: 382
-- Name: compras_insumos; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.compras_insumos ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3915 (class 0 OID 17692)
-- Dependencies: 388
-- Name: eventos_sanitarios; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.eventos_sanitarios ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3907 (class 0 OID 17547)
-- Dependencies: 372
-- Name: insumos; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.insumos ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3911 (class 0 OID 17611)
-- Dependencies: 380
-- Name: lote_origen; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.lote_origen ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3910 (class 0 OID 17596)
-- Dependencies: 378
-- Name: lotes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.lotes ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3914 (class 0 OID 17670)
-- Dependencies: 386
-- Name: movimientos_caja; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.movimientos_caja ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3913 (class 0 OID 17643)
-- Dependencies: 384
-- Name: salidas_insumos; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.salidas_insumos ENABLE ROW LEVEL SECURITY;

-- Completed on 2025-11-28 11:52:44

--
-- PostgreSQL database dump complete
--

